.PHONY: install dev test lint run clean

install:        ## Install the package (core only)
	pip install .

dev:            ## Install with dev + enrichment extras
	pip install -e ".[dev,enrich]"

test:           ## Run the test suite
	pytest -q

lint:           ## Static lint
	ruff check phishtriage tests

run:            ## Analyze all bundled samples -> reports/
	python -m phishtriage batch samples -o reports

clean:          ## Remove caches and generated bytecode
	rm -rf .pytest_cache **/__pycache__ build *.egg-info
