"""Render triage results as Markdown, JSON, or a standalone HTML report."""
from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone

from .parser import ParsedEmail
from .scoring import Result

_VERDICT_EMOJI = {
    "Benign": "🟢",
    "Suspicious": "🟡",
    "Likely Phishing": "🟠",
    "High-Confidence Phishing": "🔴",
}
_VERDICT_COLOR = {
    "Benign": "#1a7f37",
    "Suspicious": "#9a6700",
    "Likely Phishing": "#bc4c00",
    "High-Confidence Phishing": "#cf222e",
}
_RECOMMENDATIONS = {
    "Benign": "No action required. Safe to deliver; retain for baseline tuning.",
    "Suspicious": "Analyst review recommended. Consider banner/quarantine and confirm sender out-of-band.",
    "Likely Phishing": "Quarantine, warn the recipient, and hunt for other copies across mailboxes.",
    "High-Confidence Phishing": "Block sender + domains/URLs, purge from all mailboxes, and open an incident.",
}


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def to_dict(result: Result, parsed: ParsedEmail) -> dict:
    return {
        "tool": "phishtriage",
        "generated": _now(),
        "file": result.path,
        "verdict": result.verdict,
        "score": result.score,
        "authentication": {"spf": result.auth.spf, "dkim": result.auth.dkim, "dmarc": result.auth.dmarc},
        "sender": {"display_name": parsed.from_display, "address": parsed.from_addr,
                   "reply_to": parsed.reply_to, "return_path": parsed.return_path},
        "subject": parsed.subject,
        "summary": result.summary,
        "findings": [asdict(f) for f in result.findings],
        "links": [asdict(link) for link in parsed.links],
        "attachments": [asdict(a) for a in parsed.attachments],
    }


def render_json(result: Result, parsed: ParsedEmail) -> str:
    return json.dumps(to_dict(result, parsed), indent=2)


def render_markdown(result: Result, parsed: ParsedEmail) -> str:
    emoji = _VERDICT_EMOJI.get(result.verdict, "")
    L: list[str] = []
    L.append(f"# Phishing Triage Report — {emoji} {result.verdict}")
    L.append("")
    L.append(f"> **Risk score:** {result.score}  ·  **File:** `{result.path}`  ·  **Generated:** {_now()}")
    L.append("")
    L.append("## Verdict")
    L.append("")
    L.append("| Field | Value |")
    L.append("|-------|-------|")
    L.append(f"| Verdict | {emoji} **{result.verdict}** |")
    L.append(f"| Risk score | **{result.score}** |")
    L.append(f"| Findings | {result.summary['num_findings']} "
             f"({result.summary['high']} high / {result.summary['medium']} medium / {result.summary['low']} low) |")
    L.append(f"| Recommended action | {_RECOMMENDATIONS.get(result.verdict, '')} |")
    L.append("")
    L.append("## Sender & Authentication")
    L.append("")
    L.append("| Field | Value |")
    L.append("|-------|-------|")
    L.append(f"| Display name | {parsed.from_display or '—'} |")
    L.append(f"| From address | {parsed.from_addr or '—'} |")
    L.append(f"| Reply-To | {', '.join(parsed.reply_to) or '—'} |")
    L.append(f"| Return-Path | {parsed.return_path or '—'} |")
    L.append(f"| Subject | {parsed.subject or '—'} |")
    L.append(f"| SPF / DKIM / DMARC | `{result.auth.spf}` / `{result.auth.dkim}` / `{result.auth.dmarc}` |")
    L.append("")
    L.append("## Findings")
    L.append("")
    if result.findings:
        L.append("| Severity | Rule | Weight | ATT&CK | Detail |")
        L.append("|----------|------|:------:|:------:|--------|")
        for f in sorted(result.findings, key=lambda x: -x.weight):
            sev = {"high": "🔴 High", "medium": "🟠 Medium", "low": "🟡 Low"}.get(f.severity, f.severity)
            L.append(f"| {sev} | `{f.rule_id}` | {f.weight} | {f.attack} | {f.detail} |")
    else:
        L.append("_No suspicious indicators detected._")
    L.append("")
    if parsed.links:
        L.append("## Extracted Links")
        L.append("")
        L.append("| Source | Anchor text | URL |")
        L.append("|--------|-------------|-----|")
        for link in parsed.links:
            url = link.url if len(link.url) < 90 else link.url[:87] + "…"
            L.append(f"| {link.source} | {link.anchor_text or '—'} | `{url}` |")
        L.append("")
    if parsed.attachments:
        L.append("## Attachments")
        L.append("")
        L.append("| Filename | Content-Type | Size (B) | SHA-256 |")
        L.append("|----------|--------------|---------:|---------|")
        for a in parsed.attachments:
            L.append(f"| `{a.filename}` | {a.content_type} | {a.size} | `{a.sha256}` |")
        L.append("")
    L.append("---")
    L.append("")
    L.append("_Generated by [phishtriage](https://github.com/DMYourz). "
             "Offline static analysis — verify enrichment before blocking._")
    L.append("")
    return "\n".join(L)


def render_html(result: Result, parsed: ParsedEmail) -> str:
    color = _VERDICT_COLOR.get(result.verdict, "#57606a")
    rows = ""
    for f in sorted(result.findings, key=lambda x: -x.weight):
        rows += (f"<tr><td><span class='sev {f.severity}'>{f.severity}</span></td>"
                 f"<td><code>{f.rule_id}</code></td><td class='c'>{f.weight}</td>"
                 f"<td class='c'>{f.attack}</td><td>{_esc(f.detail)}</td></tr>")
    if not rows:
        rows = "<tr><td colspan='5'>No suspicious indicators detected.</td></tr>"
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Phishing Triage — {_esc(parsed.subject)[:60]}</title>
<style>
  body{{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;background:#f6f8fa;color:#1f2328}}
  .wrap{{max-width:920px;margin:24px auto;padding:0 16px}}
  .card{{background:#fff;border:1px solid #d0d7de;border-radius:10px;padding:20px;margin-bottom:16px}}
  .banner{{border-left:8px solid {color};padding:16px 20px}}
  .verdict{{font-size:24px;font-weight:700;color:{color}}}
  .score{{font-size:13px;color:#57606a}}
  table{{border-collapse:collapse;width:100%;font-size:14px}}
  th,td{{border:1px solid #d0d7de;padding:8px 10px;text-align:left;vertical-align:top}}
  th{{background:#f6f8fa}} td.c{{text-align:center}}
  code{{background:#eff1f3;padding:1px 5px;border-radius:5px;font-size:12px;word-break:break-all}}
  .sev{{padding:2px 8px;border-radius:10px;color:#fff;font-size:12px;text-transform:capitalize}}
  .sev.high{{background:#cf222e}}.sev.medium{{background:#bc4c00}}.sev.low{{background:#9a6700}}
  h2{{font-size:15px;border-bottom:1px solid #d0d7de;padding-bottom:6px;margin-top:0}}
  .kv td:first-child{{width:170px;color:#57606a;font-weight:600}}
</style></head><body><div class="wrap">
<div class="card banner"><div class="verdict">{_VERDICT_EMOJI.get(result.verdict,'')} {result.verdict}</div>
<div class="score">Risk score {result.score} · {result.summary['num_findings']} findings · {_esc(result.path)}</div></div>
<div class="card"><h2>Sender &amp; Authentication</h2><table class="kv">
<tr><td>Display name</td><td>{_esc(parsed.from_display) or '—'}</td></tr>
<tr><td>From address</td><td>{_esc(parsed.from_addr) or '—'}</td></tr>
<tr><td>Reply-To</td><td>{_esc(', '.join(parsed.reply_to)) or '—'}</td></tr>
<tr><td>Return-Path</td><td>{_esc(parsed.return_path) or '—'}</td></tr>
<tr><td>Subject</td><td>{_esc(parsed.subject) or '—'}</td></tr>
<tr><td>SPF / DKIM / DMARC</td><td><code>{result.auth.spf}</code> / <code>{result.auth.dkim}</code> / <code>{result.auth.dmarc}</code></td></tr>
</table></div>
<div class="card"><h2>Findings</h2><table>
<tr><th>Severity</th><th>Rule</th><th>Weight</th><th>ATT&amp;CK</th><th>Detail</th></tr>
{rows}</table></div>
<div class="card"><h2>Recommended action</h2><p>{_esc(_RECOMMENDATIONS.get(result.verdict,''))}</p></div>
</div></body></html>"""


def _esc(s: str) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
